### ISSUE TITLE
系统托盘中的图标显示不正确

### ISSUE THREAD

**Issue by bruceinside** [timxx/xmradio#32]
![70cba46fe36f6c8498995ac42fc4b8e3kaffeine-with-gbk-chinese-subtitle-correctly-displayed](https://cloud.githubusercontent.com/assets/6964219/3077234/2e1e0866-e41c-11e3-8d66-7bcb1cb30db9.jpg)

os: openSUSE 13.1
kde：4.11.5

**Comment by ClarkZhang** [comment]
我在opensuse 13.1和13.2下也有同样的问题，从opensuse官网下载安装的虾米
