### ISSUE TITLE
fedora21下已经无法编译了

### ISSUE THREAD

**Issue by jimmy9065** [timxx/xmradio#37]
新的GTK编译有两处deprecated了

/home/jimmy/xiami/xmradio/src/xmrlabel.c: 在函数‘xmr_label_get_type’中:
/home/jimmy/xiami/xmradio/src/xmrlabel.c:26:1: 错误：‘gtk_misc_get_type’ is deprecated (declared at /usr/include/gtk-3.0/gtk/deprecated/gtkmisc.h:70) [-Werror=deprecated-declarations]
 G_DEFINE_TYPE(XmrLabel, xmr_label, GTK_TYPE_MISC)
 ^
/home/jimmy/xiami/xmradio/src/xmrlabel.c: 在函数‘xmr_label_set_color’中:
/home/jimmy/xiami/xmradio/src/xmrlabel.c:359:3: 错误：‘gdk_color_parse’ is deprecated (declared at /usr/include/gtk-3.0/gdk/deprecated/gdkcolor.h:79) [-Werror=deprecated-declarations]
   if (gdk_color_parse(color, &gdk_color))
   ^

**Comment by timxx** [comment]
On 03/05/2015 02:16 AM, jimmy9065 wrote:
>
> 新的GTK编译有两处deprecated了
>
> /home/jimmy/xiami/xmradio/src/xmrlabel.c: 在函数‘xmr_label_get_type’中:
> /home/jimmy/xiami/xmradio/src/xmrlabel.c:26:1: 错 
> 误：‘gtk_misc_get_type’ is deprecated (declared at 
> /usr/include/gtk-3.0/gtk/deprecated/gtkmisc.h:70) 
> [-Werror=deprecated-declarations]
> G_DEFINE_TYPE(XmrLabel, xmr_label, GTK_TYPE_MISC)
> ^
> /home/jimmy/xiami/xmradio/src/xmrlabel.c: 在函数‘xmr_label_set_color’中:
> /home/jimmy/xiami/xmradio/src/xmrlabel.c:359:3: 错 
> 误：‘gdk_color_parse’ is deprecated (declared at 
> /usr/include/gtk-3.0/gdk/deprecated/gdkcolor.h:79) 
> [-Werror=deprecated-declarations]
> if (gdk_color_parse(color, &gdk_color))
> ^
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/timxx/xmradio/issues/37>.
>

先在cmake的时候加上 -DWARN_AS_ERROR=OFF吧，有时间处理一下
-- 
/Regards/
