### ISSUE TITLE
Arch - Trace/breakpoint trap

### ISSUE THREAD

**Issue by bdbai** [timxx/xmradio#41]
使用 `yaourt` 安装的 `xmradio-git`，在 xterm 下运行 `xmradio` 提示：

```bash
(xmradio:2219): GLib-GIO-ERROR **: Settings schema 'com.timxx.xmradio' is not installed

Trace/breakpoint trap (core dumped)
```

然后并不能正常运行 :(

**Comment by bdbai** [comment]
KDE 底下的毛病...无视好了

**Comment by timxx** [comment]
额，我用的也是arch，不过是xfce4，一直是用自己编译。。既然好了就先不管了，那个估计是gschema有些问题

**Comment by ruizhipeng** [comment]
@bdbai 
能问下你是怎么解决的么？我也是用kde,但是技术太差不太会，能不能安利一下怎么搞定的

**Comment by bdbai** [comment]
@ruizhipeng
换 GNOME 环境就好了。KDE 底下目测得装一大包 Gtk 全家桶，不划算。

**Comment by ruizhipeng** [comment]
@bdbai 贫贱不能移，威武不能屈，KDE不能换 
running this as root:
# glib-compile-schemas /usr/share/glib-2.0/schemas

**Comment by bdbai** [comment]
@ruizhipeng
这样就好了？👍

**Comment by ruizhipeng** [comment]
@bdbai 
当然基础的gtk组件还是要安装的，毕竟是基于gtk开发的程序
