### ISSUE TITLE
Can't find libxmradio-core.so when compiled it frome git.

### ISSUE THREAD

**Issue by kexul** [timxx/xmradio#43]
I've compiled it from git ,when I run the xmradio ,It shows "cant' find libxmradio-core.so".
Environment : Ubuntu 16.04 
ps:I find the 'xmradio' in the 'output' directory of the cmake  works!  but there is no icon in the indicator area in my xfce4 :(

**Comment by timxx** [comment]
You should add -DCMAKE_INSTALL_PREFIX=/usr, or update the source code if you prefer install to other places. (The default prefix is /usr/local)

Also add -DENABLE_APPINDICATOR=0 to cmake, since you are not use Unity desktop. It should work if you have installed the appindicator dev package.

**Comment by kexul** [comment]
yeah,I installed it to a directory in the /home .
